### ISSUE TITLE
Invalid field "safe" when updating doctrine schema

### ISSUE THREAD

**Issue by GuillQuirin** [nicoren/cron-bundle#27]
Hello,

When I try to execute the `doctrine:mongodb:schema:create` command, I receive this error :

```
Error in specification { key: { name: -1 }, unique: false, safe: false, background: false, name: "name_-1" } :: caused by :: The field 'safe' is not valid for an index specification. Specification: { key: { name: -1 }, unique: false, safe: false, background: false, name: "name_-1" }
```

It seems the value `true` set on "safe" has been deprecated (removing this line resolve the error). 

![Capture d’écran 2021-12-13 à 14 45 51](https://user-images.githubusercontent.com/11681755/145823540-c42e3d97-d26b-4a41-a4b8-911b3c72256f.png)

Module version : 1.0.1

**Comment by GuillQuirin** [comment]
EDIT : I saw it has already been fixed but in the `dev-main` branch only. Maybe incrementing the versionning release could hint future users :)

**Comment by nicoren-tangkoko** [comment]
Hi, 
thank you.

I will increment version today to resolve this problem.

if you want to participate or open some ticket, you are welcome.

Thank you.

Best regards

Nicolas RENAULT
